### ISSUE TITLE
Could not pass event BlockPhysicsEvent to racing v3.0.0

### ISSUE THREAD

**Issue by Blatower21** [TrollskogenMC/racing#68]
**Racing version**
3.0.0

**Server software including version**
Paper 1.16.2#189

**ProtocolLib version**
4.5.1

**Java version**
Example: Java 11

**Describe the bug**
When someone place a crimson_sign or warped_sign an error shows up in console.

**To Reproduce**
1. Place a crimson or warped sign
2. See the error in the console

**Expected behavior**
No error with signs related to racing plugin.

![Error](https://user-images.githubusercontent.com/31895420/93025887-20c8e800-f5d8-11ea-942c-18952369e00c.PNG)

**Comment by Blatower21** [comment]
It was an Essentials issue.

**Comment by Blatower21** [comment]
Reopening this issue. The error still showing up in console each time a player place one of the new signs in the roof (in walls it doesn't happen) or opening chests that have this signs at their sides.

**Comment by jewome62** [comment]
I confirm this bug currently on Paper 1.16.4

```
[03:27:02 ERROR]: Could not pass event BlockPhysicsEvent to racing v4.0.0
java.lang.ClassCastException: class org.bukkit.craftbukkit.v1_16_R3.block.impl.CraftFloorSign cannot be cast to class org.bukkit.block.data.type.WallSign (org.bukkit.craftbukkit.v1_16_R3.block.impl.CraftFloorSign and org.bukkit.block.data.type.WallSign are in unnamed module of loader 'app')
        at com.github.hornta.racing.SignManager.onBlockPhysics(SignManager.java:185) ~[?:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.16.4.jar:git-Paper-274]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.16.4.jar:git-Paper-274]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.4.jar:git-Paper-274]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.4.jar:git-Paper-274]
        at net.minecraft.server.v1_16_R3.World.notifyAndUpdatePhysics(World.java:495) ~[patched_1.16.4.jar:git-Paper-274]
        at net.minecraft.server.v1_16_R3.ItemStack.placeItem(ItemStack.java:319) ~[patched_1.16.4.jar:git-Paper-274]
        at net.minecraft.server.v1_16_R3.PlayerInteractManager.a(PlayerInteractManager.java:530) ~[patched_1.16.4.jar:git-Paper-274]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1535) ~[patched_1.16.4.jar:git-Paper-274]
        at net.minecraft.server.v1_16_R3.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27) ~[patched_1.16.4.jar:git-Paper-274]
        at net.minecraft.server.v1_16_R3.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[patched_1.16.4.jar:git-Paper-274]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.4.jar:git-Paper-274]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.4.jar:git-Paper-274]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.4.jar:git-Paper-274]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.4.jar:git-Paper-274]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.4.jar:git-Paper-274]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1136) ~[patched_1.16.4.jar:git-Paper-274]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1129) ~[patched_1.16.4.jar:git-Paper-274]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.4.jar:git-Paper-274]
        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1090) ~[patched_1.16.4.jar:git-Paper-274]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1004) ~[patched_1.16.4.jar:git-Paper-274]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.4.jar:git-Paper-274]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```
