### ISSUE TITLE
Console error related to Racing

### ISSUE THREAD

**Issue by EchocallingEarth** [TrollskogenMC/racing#77]
**Racing version**
racing v4.1.0

**Server software including version**
Paper 1.16.5

**ProtocolLib version**
ProtocolLib 4.6.0

**Java version**
Java 11

**Describe the bug**
Console error - No one is using or interacting with race plugin at time of error
[14:07:40] [Server thread/ERROR]: Could not pass event BlockPhysicsEvent to racing v4.1.0
java.lang.ClassCastException: class org.bukkit.craftbukkit.v1_16_R3.block.impl.CraftFloorSign cannot be cast to class org.bukkit.block.data.type.WallSign (org.bukkit.craftbukkit.v1_16_R3.block.impl.CraftFloorSign and org.bukkit.block.data.type.WallSign are in unnamed module of loader 'app')
	at com.github.hornta.racing.SignManager.onBlockPhysics(SignManager.java:185) ~[?:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.16.5.jar:git-Paper-434]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-434]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-434]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Paper-434]
	at net.minecraft.server.v1_16_R3.World.notifyAndUpdatePhysics(World.java:496) ~[patched_1.16.5.jar:git-Paper-434]
	at net.minecraft.server.v1_16_R3.ItemStack.placeItem(ItemStack.java:319) ~[patched_1.16.5.jar:git-Paper-434]
	at net.minecraft.server.v1_16_R3.PlayerInteractManager.a(PlayerInteractManager.java:530) ~[patched_1.16.5.jar:git-Paper-434]
	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1549) ~[patched_1.16.5.jar:git-Paper-434]
	at net.minecraft.server.v1_16_R3.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27) ~[patched_1.16.5.jar:git-Paper-434]
	at net.minecraft.server.v1_16_R3.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[patched_1.16.5.jar:git-Paper-434]
	at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.5.jar:git-Paper-434]
	at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-434]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-434]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-434]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-434]
	at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1132) ~[patched_1.16.5.jar:git-Paper-434]
	at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1125) ~[patched_1.16.5.jar:git-Paper-434]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Paper-434]
	at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1086) ~[patched_1.16.5.jar:git-Paper-434]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1000) ~[patched_1.16.5.jar:git-Paper-434]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:173) ~[patched_1.16.5.jar:git-Paper-434]
	at java.lang.Thread.run(Thread.java:834) [?:?]

**To Reproduce**
4. See console error above

**Expected behavior**
No errors

**Is the bug caused by another plugin?**
Appears to be independent related to Racing only

**Screenshots**
None

**Additional context**
Any other info I can provide I will gladly provide asap

**Comment by hornta** [comment]
@EchocallingEarth Do you have any join signs? How do they look?

**Comment by EchocallingEarth** [comment]
Yes I do have signs for joining Elytra races
They look like this - 

![2021-02-18_22 54 34](https://user-images.githubusercontent.com/47970978/108455493-584d5780-723c-11eb-9eb8-ec55917ed71b.png)

The center sign is of course the join sign the others are to just help direct player for things like leaving mid game if needed and getting fireworks.

Sorry for the delay in responding, work and life kept me busy.

**Comment by hornta** [comment]
I can re-create the issue now.
